import { Inter } from "next/font/google";
import "./globals.css";
import {Header} from "@/components/Header/Header";
import ClientWrapper from "@/components/ClientWrapper/ClientWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} px-3.5 pt-3 pb-56 sm:pt-14 sm:pb-96`}>
      <ClientWrapper>
          <Header />
            {children}
      </ClientWrapper>
      </body>
    </html>
  );
}
